### ISSUE TITLE
esp32 compilation error

### ISSUE THREAD

**Issue by iqubik** [GyverLibs/AccelMotor#2]
![image](https://github.com/GyverLibs/AccelMotor/assets/22661808/ea5b11ca-967c-4185-bbf0-6a9ed47dee1c)

**Comment by GyverLibs** [comment]
Of course, "arduino" esp32 core doesn't have analogwrite 🤷

**Comment by iqubik** [comment]
Алекс, привет! Я пользователь твоей stepper библиотеки и пользователь с esp32. Ругается страшно и непонятно. Хочу зачатки библиотеки для flprog запилить, а ни один тестовый скетч не запускается.

```
f:\flprog\ideV8\portable\sketchbook\libraries\GyverMotor\src\GyverMotor.cpp: In member function 'void GMotor::setPins(bool, bool, int)':
f:\flprog\ideV8\portable\sketchbook\libraries\GyverMotor\src\GyverMotor.cpp:77:46: error: 'analogWrite' was not declared in this scope
     if (_pwmC != _GM_NC) analogWrite(_pwmC, c);
                                              ^
exit status 1
Ошибка компиляции для платы ESP32 Dev Module.
```
